# 一、ndarray
## 1.ndarray的特性
### 多维性

In [1]:
import numpy as np

In [ ]:
arr=np.array(5)  #创建0维的ndarray
print(arr)
print("arr的维度",arr.ndim)  #number of dimensions

5
arr的维度 0


In [5]:
arr=np.array([1,2,3])  #创建1维的ndarray
print(arr)
print("arr的维度",arr.ndim) 

[1 2 3]
arr的维度 1


In [7]:
arr=np.array([[1,2,3],[4,5,6]])  #创建2维的ndarray
print(arr)
print("arr的维度",arr.ndim) 

[[1 2 3]
 [4 5 6]]
arr的维度 2


### 同质性

In [ ]:
arr=np.array([1,2,"hello"])  #不同的数据类型，会被强制转换成相同的数据类型
print(arr)

['1' '2' 'hello']


In [9]:
arr=np.array([1,2.5])  #不同的数据类型，会被强制转换成相同的数据类型
print(arr)

[1.  2.5]


## 2.ndarray的属性

In [26]:
arr=np.array(1)
print(arr)
print("数组的形状",arr.shape)
print("数组的维度",arr.ndim)
print("元素的个数",arr.size)
print("元素的数据类型",arr.dtype)
print("元素的转置",arr.T)

1
数组的形状 ()
数组的维度 0
元素的个数 1
元素的数据类型 int64
元素的转置 1


In [24]:
arr=np.array([1,2.5,3])
print(arr)
print("数组的形状",arr.shape)
print("数组的维度",arr.ndim)
print("元素的个数",arr.size)
print("元素的数据类型",arr.dtype)
print("元素的转置",arr.T)

[1.  2.5 3. ]
数组的形状 (3,)
数组的维度 1
元素的个数 3
元素的数据类型 float64
元素的转置 [1.  2.5 3. ]


In [25]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("数组的形状",arr.shape)
print("数组的维度",arr.ndim)
print("元素的个数",arr.size)
print("元素的数据类型",arr.dtype)
print("元素的转置",arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状 (2, 3)
数组的维度 2
元素的个数 6
元素的数据类型 int64
元素的转置 [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [29]:
#基础的创建方法
list1=[4,5,6]
arr=np.array(list1,dtype=np.float64)
print(arr.ndim)
print(arr)

1
[4. 5. 6.]


In [32]:
#copy
arr1=np.copy(arr)  #不是一个数组，只是元素相同
print(arr1)
arr1[0]=8
print(arr1)
print(arr)

[4. 5. 6.]
[8. 5. 6.]
[4. 5. 6.]


In [35]:
#预定义形状
#全0  全1  未初始化  固定值
#全0
arr=np.zeros((2,3),dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [37]:
arr=np.zeros((200,),dtype=int)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [38]:
#全1
arr=np.ones((5,8),dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [43]:
#未初始化
arr=np.empty((4,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [46]:
#固定值
arr=np.full((3,4),2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [47]:
arr1=np.zeros_like(arr)
print(arr1)
arr1=np.empty_like(arr)
print(arr1)
arr1=np.ones_like(arr)
print(arr1)
arr1=np.full_like(arr,2026)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [ ]:
#等差数列
arr=np.arange(2,11,2)  #start,end,step
print(arr)

[ 2  4  6  8 10]


In [54]:
#等间隔数列
arr=np.linspace(0,10,3)
print(arr)

[ 0.  5. 10.]


In [57]:
arr=np.linspace(0,100,5,dtype=int)
print(arr)
arr=np.arange(0,101,25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [59]:
#对数间隔数列
arr=np.logspace(0,4,3,base=2)
print(arr)

[ 1.  4. 16.]


In [60]:
arr=np.linspace(0,4,3)
print(arr)

[0. 2. 4.]


In [61]:
arr=np.logspace(0,4,3,base=3)
print(arr)

[ 1.  9. 81.]


In [62]:
arr=np.logspace(0,4,3)  #默认底数是10
print(arr)

[1.e+00 1.e+02 1.e+04]


In [6]:
#特殊矩阵
#单位矩阵：主对角线上元素为1，其他数字为0
arr=np.eye(3,4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [8]:
#对角矩阵：主对角线上非0，其他数字为0
arr=np.diag([5,1,2,3])
print(arr)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [10]:
#随机数组的生成
#生成0到1之间的随机浮点数（均匀分布）
arr=np.random.rand(2,3)
print(arr)

[[0.95938791 0.08194143 0.83281887]
 [0.95655914 0.92345143 0.59352   ]]


In [11]:
#生成指定范围区间的随机浮点数
arr=np.random.uniform(3,6,(2,3))
print(arr)

[[3.8222442  3.20952124 3.41966362]
 [4.26043344 3.04446358 5.37947857]]


In [12]:
#生成指定范围区间的随机整数
arr=np.random.randint(3,30,(2,3))
print(arr)

[[ 4 24 16]
 [12 10 21]]


In [13]:
#生成随机数列（正态分布）
arr=np.random.randn(2,3)
print(arr)

[[ 1.6916766   2.26320905 -0.0537868 ]
 [ 1.04680374  1.56501277 -1.26006327]]


In [17]:
#设置随机种子
np.random.seed(20)
arr=np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


## 4.ndarray的数据类型
布尔类型 bool
整数类型 int
浮点数 float
复数 complex

In [19]:
arr=np.array([1,0,2,0],dtype="bool")
print(arr)

[ True False  True False]


## 索引与切片

In [21]:
#一维数组的索引与切片
arr=np.random.randint(1,100,20)
print(arr)

[53 23 15  5 28 76  9  7 27 80 83 79 11 34 86 18 41 83 43 61]


In [31]:
print(arr[10])
print(arr[:])  #获取全部的数据
print(arr[2:5])   #start:end 左闭右开
print(arr[slice(2,15,3)])  #start,end,step
print(arr[(arr>10) & (arr<70)])   #布尔索引


83
[53 23 15  5 28 76  9  7 27 80 83 79 11 34 86 18 41 83 43 61]
[15  5 28]
[15 76 27 79 86]
[53 23 15 28 27 11 34 18 41 43 61]


In [ ]:
#二维数组的索引与切片
arr=np.random.randint(1,100,(4,8))
print(arr)

[[80 28 51 75 70  3 58 24]
 [96 26 42 10 67 16 66 31]
 [89 50 41 12 70  1 59 87]
 [38 69 19 10 58 15 36 76]]


In [41]:
print(arr[1,3])  #索引
print(arr[:,:])
print(arr[1,2:5])
print(arr[arr>50])
print(arr[2,:][arr[2,:]>50])  #嵌套
print(arr[:,3][arr[:,3]<30])

10
[[80 28 51 75 70  3 58 24]
 [96 26 42 10 67 16 66 31]
 [89 50 41 12 70  1 59 87]
 [38 69 19 10 58 15 36 76]]
[42 10 67]
[80 51 75 70 58 96 67 66 89 70 59 87 69 58 76]
[89 70 59 87]
[10 12 10]


## ndarray的运算

In [53]:
#算数运算
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [52]:
c=[1,2,3]
d=[4,5,6]
for i in range(len(c)):
    d[i]=d[i]+c[i]
print(d)

[5, 7, 9]


In [54]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [56]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+3)
print(a*3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [ ]:
#广播机制:1.获取形状  2.是否可以广播
#同一维度：相同、1
a=np.array([1,2,3])   #1*3
b=np.array([[4],[5],[6]])  #3*1
print(a+b)
print(b-a)
'''a
  1 2 3
  1 2 3
  1 2 3
  b
  4 4 4
  5 5 5
  6 6 6
  '''

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[3 2 1]
 [4 3 2]
 [5 4 3]]


'a\n  1 2 3\n  1 2 3\n  1 2 3\n  b\n  4 4 4\n  5 5 5\n  6 6 6\n  '

In [ ]:
a=np.array([1,2,3])   #1*3
b=np.array([[4,5]])  #1*2
print(b-a)  #不能广播，报错

ValueError: operands could not be broadcast together with shapes (1,2) (3,) 

In [63]:
#矩阵运算
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a@b)  #高代里的运算规则

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


# numpy中的常用函数
## 1.基本数学函数

In [67]:
#计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr=np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [ ]:
#计算指数  e^x=y
print(np.exp(0))

1.0


In [ ]:
#计算自然对数  lny=x
print(np.log(2.71))

0.9969486348916096


In [73]:
#正弦值、余弦值
print(np.sin(np.pi/2))
print(np.cos(np.pi))

1.0
-1.0


In [74]:
#计算绝对值
arr=np.array([-1,1,2,-3])
print(np.abs(arr))

[1 1 2 3]


In [76]:
#计算a的b次幂
print(np.power(arr,3))

[ -1   1   8 -27]


In [80]:
#四舍五入
print(np.round([3.2,4.5,8.1,9.6]))

[ 3.  4.  8. 10.]


In [82]:
#向上取整，向下取整
arr=np.array([1.6,25.1,81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [84]:
#检测缺失值NaN
np.isnan([1,2,np.nan,3])

array([False, False,  True, False])

## 2.统计函数
求和、计算平均值、计算中位数、标准差、方差

查找最大值、最小值

计算分位数、累积和、累积差

In [85]:
arr=np.random.randint(1,20,8)
print(arr)

[10  2  3 14 18 14 12  2]


In [87]:
#求和
print(np.sum([1,2,3]))

6


In [88]:
#计算平均值
print(np.mean([1,2,3]))

2.0


In [ ]:
#计算中位数  奇数个：排序后中间数值
#偶数个：中间两数的平均值
print(np.median([4,2,1]))
print(np.median([4,2,1,8]))

2.0
3.0


In [93]:
#计算标准差和方差
print(np.var([1,2,3]))
print(np.std([1,2,3]))

0.6666666666666666
0.816496580927726


In [97]:
#最大值和最小值
print(arr)
print(np.max(arr),np.argmax(arr))
print(np.min(arr),np.argmin(arr))

[10  2  3 14 18 14 12  2]
18 4
2 1


In [105]:
#分位数
#中位数
print(np.median([1,2,3]))
np.random.seed(0)
arr=np.random.randint(0,100,4)
print(arr)
print(np.median(arr))
print(np.percentile(arr,80))

2.0
[44 47 64 67]
55.5
65.2


In [107]:
#累积和、累积积
arr=np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

6
[1 3 6]
[1 2 6]


## 比较函数

比较是否大于、小于、等于

与、或、非

检查是否有一个True，是否全是True

In [111]:
#是否大于
print(np.greater([3,4,5,6,7],4))
#是否小于
print(np.less([3,4,5,6,7,8],4))
#是否等于
print(np.equal([3,4,5,6,7,8],4))
print(np.equal([3,4,5],[4,4,4]))

[False False  True  True  True]
[ True False False False False False]
[False  True False False False False]
[False  True False]


In [113]:
#与或非
print(np.logical_and([1,0],[1,1]))
print(np.logical_or([0,0],[1,1]))
print(np.logical_not([1,0]))

[ True False]
[ True  True]
[False  True]


In [117]:
#检查元素是否至少有一个元素为True
print(np.any([0,0,0,0,0]))
#是否全部为True
print(np.all([1,1]))

False
True


In [119]:
#自定义条件
#print(np.where(条件,符合条件的取值,不符合条件的取值))
arr=np.array([1,2,3,4,5])
print(np.where(arr<3,arr,0))

[1 2 0 0 0]


In [120]:
arr=np.array([1,2,3,4,5])
print(np.where(arr<3,1,0))

[1 1 0 0 0]


In [121]:
score=np.random.randint(50,100,20)
print(score)
print(np.where(score>=60,'及格','不及格'))

[53 89 59 69 71 86 73 56 74 74 62 51 88 89 73 96 74 67 87 75]
['不及格' '及格' '不及格' '及格' '及格' '及格' '及格' '不及格' '及格' '及格' '及格' '不及格' '及格' '及格'
 '及格' '及格' '及格' '及格' '及格' '及格']


In [122]:
print(np.where(
    score<60,'不及格',np.where(
        score<80,'良好','优秀'
    )
))

['不及格' '优秀' '不及格' '良好' '良好' '优秀' '良好' '不及格' '良好' '良好' '良好' '不及格' '优秀' '优秀'
 '良好' '优秀' '良好' '良好' '优秀' '良好']


In [124]:
#np.select(条件，返回条件)
print(np.select([score>80,(score>60)&(score<80),score<60],
                ['优秀','良好','不及格'],
                default='未知'))

['不及格' '优秀' '不及格' '良好' '良好' '优秀' '良好' '不及格' '良好' '良好' '良好' '不及格' '优秀' '优秀'
 '良好' '优秀' '良好' '良好' '优秀' '良好']


In [8]:
#排序函数
np.random.seed(0)
arr=np.random.randint(1,100,20)
print(arr)
#arr.sort()
#print(arr)
print(np.sort(arr))
print(np.argsort(arr))
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [9]:
#去重函数
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [11]:
#数组的拼接
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)
print(np.concatenate((arr1,arr2)))

[5 7 9]
[1 2 3 4 5 6]


In [14]:
#数组的分割
print(np.split(arr,5))
print(np.split(arr,[6,12,18]))

[array([45, 48, 65, 68], dtype=int32), array([68, 10, 84, 22], dtype=int32), array([37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66], dtype=int32), array([40, 88, 47, 89], dtype=int32)]
[array([45, 48, 65, 68, 68, 10], dtype=int32), array([84, 22, 37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66, 40, 88], dtype=int32), array([47, 89], dtype=int32)]


In [15]:
#调整数组的形状
print(np.reshape(arr,[4,5]))

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]


In [ ]:
'''
题目1：温度数据分析
某城市一周的最高气温为[28,38,29,31,32,30,29]
-计算平均气温、最高气温和最低气温
-找出气温超过30的天数
'''

'\n题目1：温度数据分析\n某城市一周的最高气温为[28,38,29,31,32,30,29]\n-计算平均气温、最高气温和最低气温\n-找出气温超过30的天气\n'

In [18]:
import numpy as np
temps=np.array([28,38,29,31,32,30,29])
print(temps)
print('%.3f'%np.mean(temps))
print('%.3f'%np.max(temps))
print('%.3f'%np.min(temps))
print(len(temps[temps>30]))

[28 38 29 31 32 30 29]
31.000
38.000
28.000
3


In [ ]:
'''
题目2：学生成绩统计
某班级5名学生成绩为[85,90,78,92,88]
-计算成绩的平均值、中位数和标准差
-将成绩转化为百分制（假设满分10分）
'''

In [ ]:
score=np.array([85,90,78,92,88])
print(np.mean(score))
print(np.median(score))
print('%.3f'%np.std(score))
print()

86.6
88.0
4.883


In [ ]:
'''
题目3：矩阵运算
给定矩阵A=[[1,2,],[3,4]],B=[[5,6],[7,8]]
-计算A+B,A*B(逐个元素乘法)
-计算A和B的矩阵乘法(点积)
'''

In [23]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A+B)
print(A*B)
print(A@B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
'''
题目4：随机数据的生成
生成一个(3,4)的随机整数数组，范围[0,10)
-计算每列的最大值和每行的最小值
-将数组的所有奇数替换成-1
'''

In [35]:
np.random.seed(0)
arr=np.random.randint(0,10,(3,4))
print(arr)
print(np.max(arr,axis=0))  #axis=0代表列   axis=1代表行
print(np.min(arr,axis=1))
print(np.where(arr%2==1,-1,arr))
arr[0][0]=-1
arr[1]=-1
arr[:,0]=-1
print(arr)
arr[arr%2==1]=-1
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[7 9 7 6]
[0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0  3  3]
 [-1 -1 -1 -1]
 [-1  4  7  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [-1  4 -1  6]]


In [ ]:
'''
题目5：数组的变形
创建一个1到12的一维数组，并转换成(3,4)的二维数组
-计算每行的和、每列的平均值
-将数组展平为一维数组
'''

In [42]:
arr=np.arange(1,13)
print(arr)
arr=np.reshape(arr,(3,4))
print(np.sum(arr,axis=1))
print(np.mean(arr,axis=0))
arr=np.reshape(arr,(12))
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[10 26 42]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
'''
题目6：布尔索引
生成一个(5,5)的随机数组，范围[0,20)
-找出数组中大于10的元素
-将所有大于10的元素替换成0
'''

In [46]:
np.random.seed(0)
arr=np.random.randint(0,20,(5,5))
print(arr)
print(arr[arr>10])
arr[arr>10]=0
print(arr)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [ ]:
'''
题目7：统计函数应用
某公司6个月的销售额为[120,135,110,125,130,140]
-计算销售额的总和、均值和方差
-找出销售额最高的月份和最低的月份
'''

In [47]:
money=np.array([120,135,110,125,130,140])
print(np.sum(money))
print(np.mean(money))
print(np.var(money))
print(np.argmax(money)+1)
print(np.argmin(money)+1)


760
126.66666666666667
97.22222222222223
6
3


In [ ]:
'''
题目8：数组拼接
给定A=[1,2,3]  B=[4,5,6]
-将A和B水平拼接为一个新数组
-将A和B垂直拼接为一个新数组
'''

In [50]:
A=np.array([1,2,3])
B=np.array([4,5,6])
C=np.concatenate([A,B])
print(C)
print(np.reshape(C,(2,3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
'''
题目9：唯一值与排序
给定数组[2,1,2,3,1,4,3]
-找出数组中的唯一值并排序
-计算每个唯一值出现的次数
'''

In [58]:
arr=np.array([2,1,2,3,1,4,3])
u_arr,counts=np.unique(arr,return_counts=True)
print(u_arr)
print(counts)
d=[]
for i in range(len(u_arr)):
    d=d+[len(arr[arr==u_arr[i]])]
print(d)


[1 2 3 4]
[2 2 2 1]
[2, 2, 2, 1]


In [ ]:
'''
题目10：综合应用
某商店5天的销售额和成本如下：
销售额[20,25,22,30,28]
成本[15,18,16,22,20]
-计算每天的利润
-计算利润的平均值和标准差
-找出利润最高的天数
'''

In [62]:
money=np.array([20,25,22,30,28])
a=np.array([15,18,16,22,20])
print(money-a)
b=money-a
print(np.mean(b))
print(np.std(b))
print(len(b[b==np.max(b)]))

[5 7 6 8 8]
6.8
1.16619037896906
2
